---
general:
  user-agent: "okhttp/4.1.0"
  content-type: "application/x-www-form-urlencoded"
  content-language: "en_US"

ema:
  host: "www.apsystemsema.cn"
  port: 9035
  key: !ENV ${EMA_KEY}
  access_token: !ENV ${EMA_ACCESS_TOKEN}
  checkcode: !ENV ${EMA_CHECKCODE}
  username: !ENV ${EMA_USERNAME}
  password: !ENV ${EMA_PASSWORD}