---
general:
  user-agent: "okhttp/4.1.0"
  content-type: "application/x-www-form-urlencoded"
  content-language: "en_US"

ema:
  host: "www.apsystemsema.cn"
  port: 9035
  access_token: !ENV ${EMA_ACCESS_TOKEN}
  key: !ENV ${EMA_KEY}
  secret_key: !ENV ${EMA_SECRET_KEY}
  salt_key: !ENV ${EMA_SALT_KEY}
  salt_value: !ENV ${EMA_SALT_VALUE}
  username: !ENV ${EMA_USERNAME}
  password: !ENV ${EMA_PASSWORD}